language: python

python:
  - 2.7
install: pip install -r requirements.txt
services:
  - postgresql
branches:
  only:
    - master

before_script:
  - psql -c 'create database testing;' -U postgres
script: python manage.py test
