"""empty message

Revision ID: 03e84b7369b8
Revises: 
Create Date: 2017-07-17 07:13:32.106152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03e84b7369b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('instance_id', sa.String(), nullable=False))
    op.drop_column('workers', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=False))
    op.drop_column('workers', 'instance_id')
    # ### end Alembic commands ###
