"""empty message

Revision ID: d0ac137691fd
Revises: d3144d5d2f80
Create Date: 2017-07-28 23:30:48.388656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ac137691fd'
down_revision = 'd3144d5d2f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
